// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.24.0

package sqlrepo

import ()

type Counter struct {
	ID    string
	Value int64
}

type Gauge struct {
	ID    string
	Value float64
}
