// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.24.0

package sqlrepo

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Counter struct {
	ID    string
	Delta pgtype.Int8
}

type Gauge struct {
	ID    string
	Value pgtype.Float8
}
