#!/bin/bash

# этот скрипт запускает агнет и сервер
# и профилирует их работу в связке

# arg - output file

PPROF_SERVER="localhost:6060"
PROFILE_TYPE="heap"

# проверяем что в первом аргументе не нулевая строка,
# это делается при помощи -z
if [ -z $1 ]; then
    echo "usage $0 [output-file]";
    exit 1
fi

## в конце скрипта вырубим все фоновые процессы
trap "trap - SIGTERM && kill -- -$$" SIGINT SIGTERM EXIT

# удалим если было записано
unlink $1

# запускаем агент и сервер
go run ./cmd/server -profile&
go run ./cmd/agent&

# профилируем, но сначала даем время серверам запуститься
sleep 1
curl http://$PPROF_SERVER/debug/pprof/heap?seconds=30 > $1

# говово
echo "Профилирование завершено! Посмотреть можно командной: "
echo "use go tool -http=:9090 $1"
#go tool pprof -http=":9090" -seconds=30 http://localhost:6060/debug/pprof/heap

#curl -sK -v http://$PPROF_SERVER/debug/pprof/heap > $1
#go tool pprof -http=":9090" -seconds=30 $1

# go tool pprof -seconds=30 http://$PPROF_SERVER/debug/pprof/$PROFILE_TYPE