version: "2"
sql:
  - engine: "postgresql"
    queries: "query.sql"
    schema: "../migrations"
    gen:
      go:
        package: "sqlrepo"
        out: "../../internal/server/storagev2/sqlrepo"
        sql_package: "pgx/v5"