#!/bin/bash
# Этот скрипт позволяет протестировать клиент, вывести его покрытие в браузере
# удаляет все лишние файлы
t="./.cover-profile.$$"
go test ./cmd/agent -coverprofile $t
go tool cover -html=$t
rm $t