name: autotests

on:
  pull_request:
  push:

jobs:

  coverage_badge:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Create Awesome Badge
        uses: schneegans/dynamic-badges-action@v1.7.0
        with:
          auth: ${{ secrets.GIST_TOKEN }}
          gistID: ${{ vars.BADGE_GIST_ID}}
          filename: ${{ github.ref_name }}.json # Use test.svg if you want to use the SVG mode.
          label: Hello
          message: World
          color: orange

